import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import pptxgen from 'pptxgenjs';

export const downloadBlob = (blob, fileName) => {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.style.display = 'none';
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(a);
};

export const captureElement = async (elementId) => {
  const element = document.getElementById(elementId);
  if (!element) throw new Error(`Element ${elementId} not found`);
  
  // Make sure element is visible and style is correct for capture
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: document.documentElement.classList.contains('dark') ? '#020617' : '#f8fafc',
    logging: false
  });
  
  return canvas;
};

export const exportToPDF = async (elementId, fileName) => {
  const canvas = await captureElement(elementId);
  const imgData = canvas.toDataURL('image/png');
  
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });
  
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
  
  pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
  
  // If content is taller than A4 page, add new pages
  let heightLeft = pdfHeight - pdf.internal.pageSize.getHeight();
  let position = -pdf.internal.pageSize.getHeight();
  
  while (heightLeft >= 0) {
    position = position - pdf.internal.pageSize.getHeight();
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
    heightLeft -= pdf.internal.pageSize.getHeight();
  }
  
  pdf.save(fileName.endsWith('.pdf') ? fileName : `${fileName}.pdf`);
};

export const exportToPNG = async (elementId, fileName) => {
  const canvas = await captureElement(elementId);
  const dataUrl = canvas.toDataURL('image/png');
  
  const a = document.createElement('a');
  a.href = dataUrl;
  a.download = fileName.endsWith('.png') ? fileName : `${fileName}.png`;
  a.click();
};

export const exportToExcel = (data, headers, fileName) => {
  const worksheet = XLSX.utils.json_to_sheet(data, { header: headers });
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Data");
  
  XLSX.writeFile(workbook, fileName.endsWith('.xlsx') ? fileName : `${fileName}.xlsx`);
};

export const exportToCSV = (data, headers, fileName) => {
  const escapeCSV = (val) => {
    if (val === null || val === undefined) return '""';
    const str = String(val);
    if (str.includes(',') || str.includes('\n') || str.includes('"')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const csvRows = [];
  
  // Header row
  csvRows.push(headers.map(escapeCSV).join(','));
  
  // Data rows
  data.forEach(row => {
    const rowValues = headers.map(h => escapeCSV(row[h]));
    csvRows.push(rowValues.join(','));
  });
  
  const blob = new Blob([new Uint8Array([0xEF, 0xBB, 0xBF]), csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' }); // Added BOM for Excel UTF-8
  downloadBlob(blob, fileName.endsWith('.csv') ? fileName : `${fileName}.csv`);
};

export const exportToPowerPoint = (title, slides, fileName) => {
  const pres = new pptxgen();
  pres.layout = 'LAYOUT_16x9';
  
  // Title slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: '0f172a' };
  titleSlide.addText(title, { x: 1, y: 2, w: '80%', h: 1, fontSize: 36, color: 'ffffff', bold: true, align: 'center' });
  titleSlide.addText("Generated by AI Excel Analyzer", { x: 1, y: 3, w: '80%', h: 1, fontSize: 18, color: '94a3b8', align: 'center' });
  
  // Content slides
  slides.forEach(s => {
    const slide = pres.addSlide();
    slide.background = { color: 'ffffff' };
    
    // Title
    slide.addText(s.title, { x: 0.5, y: 0.5, w: '90%', h: 0.5, fontSize: 24, color: '0f172a', bold: true });
    
    if (s.imageBase64) {
       slide.addImage({ data: s.imageBase64, x: 0.5, y: 1.2, w: '90%', h: 4 });
    } else if (s.content) {
       // Very basic markdown stripping
       const cleanContent = s.content.replace(/#|\*|_|`/g, '');
       slide.addText(cleanContent, { x: 0.5, y: 1.2, w: '90%', h: 4, fontSize: 14, color: '334155', valign: 'top' });
    }
  });
  
  pres.writeFile({ fileName: fileName.endsWith('.pptx') ? fileName : `${fileName}.pptx` });
};
